name: Build and Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Create .env file
      run: |
        echo ${{ secrets.ENV_FILE }} > .env


    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/private:be .

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/private:be

  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Copy SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: SSH into EC2 and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/private:be
          sudo docker stop private-be || true
          sudo docker rm private-be || true
          sudo docker run -d --name private-be -p 80:2000 ${{ secrets.DOCKER_USERNAME }}/private:be
        EOF
